services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        SITE_URL: ${APP_URL}
    container_name: ${NEXTJS_CONTAINER_NAME:-boilerplate-next-prod}
    ports:
      - "${APP_PORT:-3000}:3000"
    networks:
      - ${PROXY_NETWORK_NAME:?err_proxy_network_not_defined}
    depends_on:
      - postgres
    environment:
      - APP_URL=${APP_URL}
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_URL=${APP_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - DEFAULT_EMAIL=${DEFAULT_EMAIL:-noreply@example.com}
    user: "node"

  postgres:
    image: postgres:15-alpine
    container_name: ${POSTGRES_CONTAINER_NAME:-boilerplate-postgres-prod}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mydb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - ${PROXY_NETWORK_NAME:?err_proxy_network_not_defined}
    restart: unless-stopped

networks:
  ${PROXY_NETWORK_NAME:?err_proxy_network_not_defined}:
    external: true
volumes:
  postgres_data:
